
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gelay
 */
public class admin_dashboard extends javax.swing.JFrame {

    Color defaultColor, clickedColor;
    
    public admin_dashboard() {
        initComponents();
        defaultColor = new Color(227,0,0);
        clickedColor = new Color(255,0,0);
    }

    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account_management = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        e_receipts = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        menu_management = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payment_settings = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        log_reports = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        user_tab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        user_list = new javax.swing.JTable();
        btn_addUser = new roundPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_editUser = new roundPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_resetPassword = new roundPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_deleteUser = new roundPanel();
        jLabel14 = new javax.swing.JLabel();
        menu_tab = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        user_list1 = new javax.swing.JTable();
        btn_addMenu = new roundPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_editMenu = new roundPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_deleteMenu = new roundPanel();
        jLabel19 = new javax.swing.JLabel();
        payment_tab = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btn_editPayment = new roundPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        gcashNumber = new javax.swing.JTextField();
        gcashAvailability = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        gcash_qr = new javax.swing.JLabel();
        e_receipts_tab = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        user_list3 = new javax.swing.JTable();
        btn_addMenu2 = new roundPanel();
        jLabel24 = new javax.swing.JLabel();
        btn_editMenu2 = new roundPanel();
        jLabel25 = new javax.swing.JLabel();
        btn_deleteMenu2 = new roundPanel();
        jLabel26 = new javax.swing.JLabel();
        log_reports_tab = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        user_list2 = new javax.swing.JTable();
        btn_addMenu1 = new roundPanel();
        jLabel20 = new javax.swing.JLabel();
        btn_editMenu1 = new roundPanel();
        jLabel21 = new javax.swing.JLabel();
        btn_deleteMenu1 = new roundPanel();
        jLabel22 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(198, 0, 0));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainlogo_thumbnail.png"))); // NOI18N
        sidePane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 210));

        account_management.setBackground(new java.awt.Color(227, 0, 0));
        account_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_managementMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                account_managementMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                account_managementMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("User Account Management");

        javax.swing.GroupLayout account_managementLayout = new javax.swing.GroupLayout(account_management);
        account_management.setLayout(account_managementLayout);
        account_managementLayout.setHorizontalGroup(
            account_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, account_managementLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        account_managementLayout.setVerticalGroup(
            account_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(account_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 360, 70));

        e_receipts.setBackground(new java.awt.Color(227, 0, 0));
        e_receipts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e_receiptsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                e_receiptsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                e_receiptsMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-Receipts");

        javax.swing.GroupLayout e_receiptsLayout = new javax.swing.GroupLayout(e_receipts);
        e_receipts.setLayout(e_receiptsLayout);
        e_receiptsLayout.setHorizontalGroup(
            e_receiptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, e_receiptsLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        e_receiptsLayout.setVerticalGroup(
            e_receiptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        sidePane.add(e_receipts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 360, 70));

        logout.setBackground(new java.awt.Color(227, 0, 0));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_logo.png"))); // NOI18N
        jLabel13.setText("        Logout");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 930, 360, 70));

        menu_management.setBackground(new java.awt.Color(227, 0, 0));
        menu_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_managementMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_managementMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu_managementMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Management");

        javax.swing.GroupLayout menu_managementLayout = new javax.swing.GroupLayout(menu_management);
        menu_management.setLayout(menu_managementLayout);
        menu_managementLayout.setHorizontalGroup(
            menu_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_managementLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menu_managementLayout.setVerticalGroup(
            menu_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        sidePane.add(menu_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 360, 70));

        payment_settings.setBackground(new java.awt.Color(227, 0, 0));
        payment_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payment_settingsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                payment_settingsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                payment_settingsMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Payment Settings");

        javax.swing.GroupLayout payment_settingsLayout = new javax.swing.GroupLayout(payment_settings);
        payment_settings.setLayout(payment_settingsLayout);
        payment_settingsLayout.setHorizontalGroup(
            payment_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payment_settingsLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        payment_settingsLayout.setVerticalGroup(
            payment_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        sidePane.add(payment_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 360, 70));

        log_reports.setBackground(new java.awt.Color(227, 0, 0));
        log_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_reportsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_reportsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                log_reportsMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Log Reports");

        javax.swing.GroupLayout log_reportsLayout = new javax.swing.GroupLayout(log_reports);
        log_reports.setLayout(log_reportsLayout);
        log_reportsLayout.setHorizontalGroup(
            log_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, log_reportsLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        log_reportsLayout.setVerticalGroup(
            log_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        sidePane.add(log_reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 360, 70));

        getContentPane().add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 1020));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1920, 10));

        user_tab.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel6.setText("USER ACCOUNT MANAGEMENT");

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 5));

        user_list.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        user_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Administrator", "admin", "PC /Laptop"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type of User", "Username", "Device"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user_list.setGridColor(new java.awt.Color(230, 0, 0));
        user_list.setIntercellSpacing(new java.awt.Dimension(10, 10));
        user_list.setRowHeight(80);
        user_list.setSelectionBackground(new java.awt.Color(255, 171, 171));
        user_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        user_list.setShowVerticalLines(false);
        user_list.setSurrendersFocusOnKeystroke(true);
        user_list.getTableHeader().setResizingAllowed(false);
        user_list.getTableHeader().setReorderingAllowed(false);

        btn_addUser.setBackground(new java.awt.Color(255, 0, 0));
        btn_addUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_addUser.setRoundBottomLeft(30);
        btn_addUser.setRoundBottomRight(30);
        btn_addUser.setRoundTopLeft(30);
        btn_addUser.setRoundTopRight(30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add");

        javax.swing.GroupLayout btn_addUserLayout = new javax.swing.GroupLayout(btn_addUser);
        btn_addUser.setLayout(btn_addUserLayout);
        btn_addUserLayout.setHorizontalGroup(
            btn_addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_addUserLayout.setVerticalGroup(
            btn_addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_editUser.setBackground(new java.awt.Color(255, 0, 0));
        btn_editUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_editUser.setRoundBottomLeft(30);
        btn_editUser.setRoundBottomRight(30);
        btn_editUser.setRoundTopLeft(30);
        btn_editUser.setRoundTopRight(30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edit");

        javax.swing.GroupLayout btn_editUserLayout = new javax.swing.GroupLayout(btn_editUser);
        btn_editUser.setLayout(btn_editUserLayout);
        btn_editUserLayout.setHorizontalGroup(
            btn_editUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_editUserLayout.setVerticalGroup(
            btn_editUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_resetPassword.setBackground(new java.awt.Color(255, 0, 0));
        btn_resetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetPassword.setRoundBottomLeft(30);
        btn_resetPassword.setRoundBottomRight(30);
        btn_resetPassword.setRoundTopLeft(30);
        btn_resetPassword.setRoundTopRight(30);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset");

        javax.swing.GroupLayout btn_resetPasswordLayout = new javax.swing.GroupLayout(btn_resetPassword);
        btn_resetPassword.setLayout(btn_resetPasswordLayout);
        btn_resetPasswordLayout.setHorizontalGroup(
            btn_resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_resetPasswordLayout.setVerticalGroup(
            btn_resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_deleteUser.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteUser.setRoundBottomLeft(30);
        btn_deleteUser.setRoundBottomRight(30);
        btn_deleteUser.setRoundTopLeft(30);
        btn_deleteUser.setRoundTopRight(30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delete");

        javax.swing.GroupLayout btn_deleteUserLayout = new javax.swing.GroupLayout(btn_deleteUser);
        btn_deleteUser.setLayout(btn_deleteUserLayout);
        btn_deleteUserLayout.setHorizontalGroup(
            btn_deleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_deleteUserLayout.setVerticalGroup(
            btn_deleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout user_tabLayout = new javax.swing.GroupLayout(user_tab);
        user_tab.setLayout(user_tabLayout);
        user_tabLayout.setHorizontalGroup(
            user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_tabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(user_tabLayout.createSequentialGroup()
                        .addComponent(btn_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_editUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btn_resetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btn_deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_list, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        user_tabLayout.setVerticalGroup(
            user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_tabLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(user_list, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(user_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        if (user_list.getColumnModel().getColumnCount() > 0) {
            user_list.getColumnModel().getColumn(0).setResizable(false);
            user_list.getColumnModel().getColumn(1).setResizable(false);
            user_list.getColumnModel().getColumn(2).setResizable(false);
        }

        jTabbedPane1.addTab("tab1", user_tab);

        menu_tab.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel15.setText("MENU MANAGEMENT");

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 5));

        user_list1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        user_list1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "testing product name",  new Float(1.0), "Available"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user_list1.setGridColor(new java.awt.Color(230, 0, 0));
        user_list1.setIntercellSpacing(new java.awt.Dimension(10, 10));
        user_list1.setRowHeight(80);
        user_list1.setSelectionBackground(new java.awt.Color(255, 171, 171));
        user_list1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        user_list1.setShowVerticalLines(false);
        user_list1.setSurrendersFocusOnKeystroke(true);
        user_list1.getTableHeader().setResizingAllowed(false);
        user_list1.getTableHeader().setReorderingAllowed(false);

        btn_addMenu.setBackground(new java.awt.Color(255, 0, 0));
        btn_addMenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_addMenu.setRoundBottomLeft(30);
        btn_addMenu.setRoundBottomRight(30);
        btn_addMenu.setRoundTopLeft(30);
        btn_addMenu.setRoundTopRight(30);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add");

        javax.swing.GroupLayout btn_addMenuLayout = new javax.swing.GroupLayout(btn_addMenu);
        btn_addMenu.setLayout(btn_addMenuLayout);
        btn_addMenuLayout.setHorizontalGroup(
            btn_addMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_addMenuLayout.setVerticalGroup(
            btn_addMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_editMenu.setBackground(new java.awt.Color(255, 0, 0));
        btn_editMenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_editMenu.setRoundBottomLeft(30);
        btn_editMenu.setRoundBottomRight(30);
        btn_editMenu.setRoundTopLeft(30);
        btn_editMenu.setRoundTopRight(30);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Edit");

        javax.swing.GroupLayout btn_editMenuLayout = new javax.swing.GroupLayout(btn_editMenu);
        btn_editMenu.setLayout(btn_editMenuLayout);
        btn_editMenuLayout.setHorizontalGroup(
            btn_editMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_editMenuLayout.setVerticalGroup(
            btn_editMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_deleteMenu.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteMenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteMenu.setRoundBottomLeft(30);
        btn_deleteMenu.setRoundBottomRight(30);
        btn_deleteMenu.setRoundTopLeft(30);
        btn_deleteMenu.setRoundTopRight(30);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Delete");

        javax.swing.GroupLayout btn_deleteMenuLayout = new javax.swing.GroupLayout(btn_deleteMenu);
        btn_deleteMenu.setLayout(btn_deleteMenuLayout);
        btn_deleteMenuLayout.setHorizontalGroup(
            btn_deleteMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_deleteMenuLayout.setVerticalGroup(
            btn_deleteMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menu_tabLayout = new javax.swing.GroupLayout(menu_tab);
        menu_tab.setLayout(menu_tabLayout);
        menu_tabLayout.setHorizontalGroup(
            menu_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(menu_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menu_tabLayout.createSequentialGroup()
                        .addComponent(btn_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_editMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_deleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        menu_tabLayout.setVerticalGroup(
            menu_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_tabLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(user_list1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menu_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        if (user_list1.getColumnModel().getColumnCount() > 0) {
            user_list1.getColumnModel().getColumn(0).setResizable(false);
            user_list1.getColumnModel().getColumn(1).setResizable(false);
            user_list1.getColumnModel().getColumn(2).setResizable(false);
            user_list1.getColumnModel().getColumn(3).setResizable(false);
        }

        jTabbedPane1.addTab("tab1", menu_tab);

        payment_tab.setOpaque(false);

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel27.setText("PAYMENT SETTINGS");

        jSeparator5.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(0, 5));

        btn_editPayment.setBackground(new java.awt.Color(255, 0, 0));
        btn_editPayment.setForeground(new java.awt.Color(255, 255, 255));
        btn_editPayment.setRoundBottomLeft(30);
        btn_editPayment.setRoundBottomRight(30);
        btn_editPayment.setRoundTopLeft(30);
        btn_editPayment.setRoundTopRight(30);

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Edit");

        javax.swing.GroupLayout btn_editPaymentLayout = new javax.swing.GroupLayout(btn_editPayment);
        btn_editPayment.setLayout(btn_editPaymentLayout);
        btn_editPaymentLayout.setHorizontalGroup(
            btn_editPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        btn_editPaymentLayout.setVerticalGroup(
            btn_editPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel31.setText("GCASH PAYMENT SETTINGS");

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel32.setText("Availability: ");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel33.setText("Gcash Number : ");

        gcashNumber.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N

        gcashAvailability.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N

        gcash_qr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gcash_qr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gcash_qr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(gcash_qr)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout payment_tabLayout = new javax.swing.GroupLayout(payment_tab);
        payment_tab.setLayout(payment_tabLayout);
        payment_tabLayout.setHorizontalGroup(
            payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_tabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payment_tabLayout.createSequentialGroup()
                        .addGroup(payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gcashNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gcashAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(payment_tabLayout.createSequentialGroup()
                        .addGroup(payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_editPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        payment_tabLayout.setVerticalGroup(
            payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payment_tabLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(payment_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payment_tabLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel33)
                        .addGap(48, 48, 48)
                        .addComponent(gcashNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel32)
                        .addGap(49, 49, 49)
                        .addComponent(gcashAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(btn_editPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", payment_tab);

        e_receipts_tab.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel23.setText("E - RECEIPTS");

        jSeparator4.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 5));

        user_list3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        user_list3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "testing product name",  new Float(1.0), "Available"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user_list3.setGridColor(new java.awt.Color(230, 0, 0));
        user_list3.setIntercellSpacing(new java.awt.Dimension(10, 10));
        user_list3.setRowHeight(80);
        user_list3.setSelectionBackground(new java.awt.Color(255, 171, 171));
        user_list3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        user_list3.setShowVerticalLines(false);
        user_list3.setSurrendersFocusOnKeystroke(true);
        user_list3.getTableHeader().setResizingAllowed(false);
        user_list3.getTableHeader().setReorderingAllowed(false);

        btn_addMenu2.setBackground(new java.awt.Color(255, 0, 0));
        btn_addMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btn_addMenu2.setRoundBottomLeft(30);
        btn_addMenu2.setRoundBottomRight(30);
        btn_addMenu2.setRoundTopLeft(30);
        btn_addMenu2.setRoundTopRight(30);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Add");

        javax.swing.GroupLayout btn_addMenu2Layout = new javax.swing.GroupLayout(btn_addMenu2);
        btn_addMenu2.setLayout(btn_addMenu2Layout);
        btn_addMenu2Layout.setHorizontalGroup(
            btn_addMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_addMenu2Layout.setVerticalGroup(
            btn_addMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_editMenu2.setBackground(new java.awt.Color(255, 0, 0));
        btn_editMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btn_editMenu2.setRoundBottomLeft(30);
        btn_editMenu2.setRoundBottomRight(30);
        btn_editMenu2.setRoundTopLeft(30);
        btn_editMenu2.setRoundTopRight(30);

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Edit");

        javax.swing.GroupLayout btn_editMenu2Layout = new javax.swing.GroupLayout(btn_editMenu2);
        btn_editMenu2.setLayout(btn_editMenu2Layout);
        btn_editMenu2Layout.setHorizontalGroup(
            btn_editMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_editMenu2Layout.setVerticalGroup(
            btn_editMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_deleteMenu2.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteMenu2.setRoundBottomLeft(30);
        btn_deleteMenu2.setRoundBottomRight(30);
        btn_deleteMenu2.setRoundTopLeft(30);
        btn_deleteMenu2.setRoundTopRight(30);

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Delete");

        javax.swing.GroupLayout btn_deleteMenu2Layout = new javax.swing.GroupLayout(btn_deleteMenu2);
        btn_deleteMenu2.setLayout(btn_deleteMenu2Layout);
        btn_deleteMenu2Layout.setHorizontalGroup(
            btn_deleteMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_deleteMenu2Layout.setVerticalGroup(
            btn_deleteMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout e_receipts_tabLayout = new javax.swing.GroupLayout(e_receipts_tab);
        e_receipts_tab.setLayout(e_receipts_tabLayout);
        e_receipts_tabLayout.setHorizontalGroup(
            e_receipts_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(e_receipts_tabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(e_receipts_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(e_receipts_tabLayout.createSequentialGroup()
                        .addComponent(btn_addMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_editMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_deleteMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(e_receipts_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_list3, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        e_receipts_tabLayout.setVerticalGroup(
            e_receipts_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(e_receipts_tabLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(user_list3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(e_receipts_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        if (user_list3.getColumnModel().getColumnCount() > 0) {
            user_list3.getColumnModel().getColumn(0).setResizable(false);
            user_list3.getColumnModel().getColumn(1).setResizable(false);
            user_list3.getColumnModel().getColumn(2).setResizable(false);
            user_list3.getColumnModel().getColumn(3).setResizable(false);
        }

        jTabbedPane1.addTab("tab1", e_receipts_tab);

        log_reports_tab.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel18.setText("MENU MANAGEMENT");

        jSeparator3.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 5));

        user_list2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        user_list2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "testing product name",  new Float(1.0), "Available"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user_list2.setGridColor(new java.awt.Color(230, 0, 0));
        user_list2.setIntercellSpacing(new java.awt.Dimension(10, 10));
        user_list2.setRowHeight(80);
        user_list2.setSelectionBackground(new java.awt.Color(255, 171, 171));
        user_list2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        user_list2.setShowVerticalLines(false);
        user_list2.setSurrendersFocusOnKeystroke(true);
        user_list2.getTableHeader().setResizingAllowed(false);
        user_list2.getTableHeader().setReorderingAllowed(false);

        btn_addMenu1.setBackground(new java.awt.Color(255, 0, 0));
        btn_addMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_addMenu1.setRoundBottomLeft(30);
        btn_addMenu1.setRoundBottomRight(30);
        btn_addMenu1.setRoundTopLeft(30);
        btn_addMenu1.setRoundTopRight(30);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Add");

        javax.swing.GroupLayout btn_addMenu1Layout = new javax.swing.GroupLayout(btn_addMenu1);
        btn_addMenu1.setLayout(btn_addMenu1Layout);
        btn_addMenu1Layout.setHorizontalGroup(
            btn_addMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_addMenu1Layout.setVerticalGroup(
            btn_addMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_editMenu1.setBackground(new java.awt.Color(255, 0, 0));
        btn_editMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_editMenu1.setRoundBottomLeft(30);
        btn_editMenu1.setRoundBottomRight(30);
        btn_editMenu1.setRoundTopLeft(30);
        btn_editMenu1.setRoundTopRight(30);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Edit");

        javax.swing.GroupLayout btn_editMenu1Layout = new javax.swing.GroupLayout(btn_editMenu1);
        btn_editMenu1.setLayout(btn_editMenu1Layout);
        btn_editMenu1Layout.setHorizontalGroup(
            btn_editMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_editMenu1Layout.setVerticalGroup(
            btn_editMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        btn_deleteMenu1.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteMenu1.setRoundBottomLeft(30);
        btn_deleteMenu1.setRoundBottomRight(30);
        btn_deleteMenu1.setRoundTopLeft(30);
        btn_deleteMenu1.setRoundTopRight(30);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Delete");

        javax.swing.GroupLayout btn_deleteMenu1Layout = new javax.swing.GroupLayout(btn_deleteMenu1);
        btn_deleteMenu1.setLayout(btn_deleteMenu1Layout);
        btn_deleteMenu1Layout.setHorizontalGroup(
            btn_deleteMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_deleteMenu1Layout.setVerticalGroup(
            btn_deleteMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout log_reports_tabLayout = new javax.swing.GroupLayout(log_reports_tab);
        log_reports_tab.setLayout(log_reports_tabLayout);
        log_reports_tabLayout.setHorizontalGroup(
            log_reports_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_reports_tabLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(log_reports_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(log_reports_tabLayout.createSequentialGroup()
                        .addComponent(btn_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_editMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_deleteMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(log_reports_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_list2, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        log_reports_tabLayout.setVerticalGroup(
            log_reports_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_reports_tabLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(user_list2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(log_reports_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        if (user_list2.getColumnModel().getColumnCount() > 0) {
            user_list2.getColumnModel().getColumn(0).setResizable(false);
            user_list2.getColumnModel().getColumn(1).setResizable(false);
            user_list2.getColumnModel().getColumn(2).setResizable(false);
            user_list2.getColumnModel().getColumn(3).setResizable(false);
        }

        jTabbedPane1.addTab("tab1", log_reports_tab);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 1560, 1000));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -6, 1920, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void account_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_managementMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_account_managementMouseClicked

    private void account_managementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_managementMousePressed
        account_management.setBackground(clickedColor);
        menu_management.setBackground(defaultColor);
        payment_settings.setBackground(defaultColor);
        e_receipts.setBackground(defaultColor);
        log_reports.setBackground(defaultColor);
        logout.setBackground(defaultColor);
    }//GEN-LAST:event_account_managementMousePressed

    private void account_managementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_managementMouseReleased

    }//GEN-LAST:event_account_managementMouseReleased

    private void e_receiptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e_receiptsMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_e_receiptsMouseClicked

    private void e_receiptsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e_receiptsMousePressed
        account_management.setBackground(defaultColor);
        menu_management.setBackground(defaultColor);
        payment_settings.setBackground(defaultColor);
        e_receipts.setBackground(clickedColor);
        log_reports.setBackground(defaultColor);
        logout.setBackground(defaultColor);
    }//GEN-LAST:event_e_receiptsMousePressed

    private void e_receiptsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e_receiptsMouseReleased

    }//GEN-LAST:event_e_receiptsMouseReleased

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        login li = new login();
        li.setVisible(true);
        close();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        account_management.setBackground(defaultColor);
        menu_management.setBackground(defaultColor);
        payment_settings.setBackground(defaultColor);
        e_receipts.setBackground(defaultColor);
        log_reports.setBackground(defaultColor);
        logout.setBackground(clickedColor);
    }//GEN-LAST:event_logoutMousePressed

    private void menu_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_managementMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_menu_managementMouseClicked

    private void menu_managementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_managementMousePressed
        account_management.setBackground(defaultColor);
        menu_management.setBackground(clickedColor);
        payment_settings.setBackground(defaultColor);
        e_receipts.setBackground(defaultColor);
        log_reports.setBackground(defaultColor);
        logout.setBackground(defaultColor);
    }//GEN-LAST:event_menu_managementMousePressed

    private void menu_managementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_managementMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_managementMouseReleased

    private void payment_settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_settingsMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_payment_settingsMouseClicked

    private void payment_settingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_settingsMousePressed
        account_management.setBackground(defaultColor);
        menu_management.setBackground(defaultColor);
        payment_settings.setBackground(clickedColor);
        e_receipts.setBackground(defaultColor);
        log_reports.setBackground(defaultColor);
        logout.setBackground(defaultColor);
    }//GEN-LAST:event_payment_settingsMousePressed

    private void payment_settingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_settingsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_payment_settingsMouseReleased

    private void log_reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_reportsMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_log_reportsMouseClicked

    private void log_reportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_reportsMousePressed
        account_management.setBackground(defaultColor);
        menu_management.setBackground(defaultColor);
        payment_settings.setBackground(defaultColor);
        e_receipts.setBackground(defaultColor);
        log_reports.setBackground(clickedColor);
        logout.setBackground(defaultColor);
    }//GEN-LAST:event_log_reportsMousePressed

    private void log_reportsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_reportsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_log_reportsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account_management;
    private javax.swing.JLabel background;
    private roundPanel btn_addMenu;
    private roundPanel btn_addMenu1;
    private roundPanel btn_addMenu2;
    private roundPanel btn_addUser;
    private roundPanel btn_addUser3;
    private roundPanel btn_deleteMenu;
    private roundPanel btn_deleteMenu1;
    private roundPanel btn_deleteMenu2;
    private roundPanel btn_deleteUser;
    private roundPanel btn_editMenu;
    private roundPanel btn_editMenu1;
    private roundPanel btn_editMenu2;
    private roundPanel btn_editPayment;
    private roundPanel btn_editUser;
    private roundPanel btn_resetPassword;
    private javax.swing.JPanel e_receipts;
    private javax.swing.JPanel e_receipts_tab;
    private javax.swing.JTextField gcashAvailability;
    private javax.swing.JTextField gcashNumber;
    private javax.swing.JLabel gcash_qr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel log_reports;
    private javax.swing.JPanel log_reports_tab;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menu_management;
    private javax.swing.JPanel menu_tab;
    private javax.swing.JPanel payment_settings;
    private javax.swing.JPanel payment_tab;
    private roundPanel roundPanel2;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTable user_list;
    private javax.swing.JTable user_list1;
    private javax.swing.JTable user_list2;
    private javax.swing.JTable user_list3;
    private javax.swing.JPanel user_tab;
    // End of variables declaration//GEN-END:variables
}
