
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gelay
 */
public class audit_modal extends javax.swing.JFrame {

    /**
     * Creates new form audit_modal
     */
    
    Double total_amount;
    int total_quantity;
    
    public audit_modal() {
        initComponents();
        txtPassword.hide();
        this.total_amount = Double.valueOf(DatabaseConnection.getInstance().auditValidation());
        System.out.println("total_amount " + total_amount);
    }
    
    
    public ArrayList getPasswordVerification(){
        ArrayList<User> passwordList = new ArrayList<User>();
        passwordList = DatabaseConnection.getInstance().getPasswordVerification();
        return passwordList;
    }
    
    public void passList(){
        if(!getPasswordVerification().isEmpty()){
            ArrayList<User> passwordList = getPasswordVerification();
            String password = String.valueOf(txtPassword.getPassword());
            for(int position = 0; position < passwordList.size(); position++){
                if(password.equals(passwordList.get(position).getUser_name().toString())){
                    login li = new login();
                    dashboard db = new dashboard();
                    if (li.isVisible()){
                        li.setVisible(false);
                        li.setVisible(true);
                        db.setVisible(false);
                        close();
                    } else {
                        li.setVisible(true);
                        db.setVisible(false);
                        close();
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null, "Something went wrong, please contact the administrator or manager in charge.", "Error", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
    }
    
//    public ArrayList auditValidation(){
//        ArrayList<OrderItems> orderListQueue = new ArrayList<OrderItems>();
//        orderListQueue = DatabaseConnection.getInstance().auditValidation();
//        return orderListQueue;
//    }
//
//    public void audit(){
//        if(!auditValidation().isEmpty()){
//            ArrayList<OrderItems> orderArrayList = auditValidation();
//            Object rowData[] = new Object[4];
//            for(int position = 0; position < orderArrayList.size(); position++){
//                rowData[0] = orderArrayList.get(position).getTotal_amount();
//                this.total_amount = this.total_amount + Double.valueOf(rowData[0].toString());
//            }
//        }
//    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        audit_amount = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Audit Tally");
        setName("audit"); // NOI18N
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_logo.png"))); // NOI18N
        jLabel6.setText("Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please enter amount:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        submit.setBackground(new java.awt.Color(255, 0, 0));
        submit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 230, 70));

        Print.setBackground(new java.awt.Color(255, 0, 0));
        Print.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 230, 70));

        audit_amount.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        audit_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(audit_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 480, 80));

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("pass");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 480, 70));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_background.png"))); // NOI18N
        bg.setToolTipText("");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 660, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        
        try{
            JasperDesign jasper = JRXmlLoader.load("C:\\Users\\Gelay\\Documents\\menuBytes_admin\\src\\audit_tally.jrxml");
            
            HashMap<String, Object> params = new HashMap<>();
            params.put("total", DatabaseConnection.getInstance().auditValidation());
            
            JasperReport jasperReport = JasperCompileManager.compileReport(jasper);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DatabaseConnection.getConnection());
            
            JasperViewer.viewReport(jasperPrint, false);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    
    }//GEN-LAST:event_PrintActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        close();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (txtPassword.getText().equals("pass")){
            String audit = String.format("%.2f", Double.parseDouble(audit_amount.getText()));
            String total = String.format("%.2f", this.total_amount);
            System.out.println ("audit " + audit);
            System.out.println ("total " + total);
            if(audit.equals(total)){
                txtPassword.show();
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong, please contact the administrator or manager in charge.", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        } else { 
            passList();
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(audit_modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(audit_modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(audit_modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(audit_modal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new audit_modal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JTextField audit_amount;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
